[transitions]


[transitions.ORDER_BY]
task="""
Select whether you would like to include an ORDER BY \
clause.
"""
[transitions.ORDER_BY.options]
1=""
2=""
[transitions.ORDER_BY.option_nodes]
1="EXIT_ORDER_BY"
2="order_by_list"


[transitions.order_by_list]
task="""
"""
[transitions.order_by_list.options]
1=""
2=""
[transitions.order_by_list.option_nodes]
1="order_by_select_reference"
2="order_by_expr"


[transitions.order_by_expr_done]
task="""
"""
[transitions.order_by_expr_done.options]
1=""
2=""
3=""
[transitions.order_by_expr_done.option_nodes]
1="order_by_order_selected"
2="order_by_asc"
3="order_by_desc"


[transitions.order_by_expr]
task="""
"""
[transitions.order_by_expr.options]
1=""
2=""
[transitions.order_by_expr.option_nodes]
1="call84_types"
2="call85_types"


[transitions.order_by_order_selected]
task="""
"""
[transitions.order_by_order_selected.options]
1=""
2=""
3=""
[transitions.order_by_order_selected.option_nodes]
1="order_by_nulls_first_selected"
2="order_by_nulls_first"
3="order_by_nulls_last"


[transitions.order_by_nulls_first_selected]
task="""
"""
[transitions.order_by_nulls_first_selected.options]
1=""
2=""
[transitions.order_by_nulls_first_selected.option_nodes]
1="order_by_list"
2="EXIT_ORDER_BY"


[call_node_context]
call84_types=""
call85_types=""


[value_chooser_tasks]
select_alias_order_by="Choose a select alias that you with to place in ORDER BY:"
