[transitions]
# HOW TO ADD THE DECISION PROMPTS:
# [transitions.node]
# task="""
# """
# [transitions.node.options]
# 1=""
# 2=""
# [transitions.node.option_nodes]
# 1=""
# 2=""


[transitions.call0_FROM]
task="""
Select which clause you would like to build next and which ones you \
would like to omit.

Note that when you choose to add the GROUP BY clause, you are only \
effectively indicating that you want your query to be groupped, and \
you can still choose to make the grouping implicit. In other words, \
choose the "add the GROUP BY clause" option if you want a query such as:
SELECT SUM(C1) FROM T1;
where the grouping is present but is implicit.
"""
[transitions.call0_FROM.options]
1="Add the WHERE clause"
2="Omit the WHERE clause, and add the GROUP BY clause"
3="Omit the WHERE clause and the GROUP BY clause, and add the SELECT clause"
[transitions.call0_FROM.option_nodes]
1="call0_WHERE"
2="call0_GROUP_BY"
3="call0_SELECT"


[transitions.call0_WHERE]
task="""
"""
[transitions.call0_WHERE.options]
1=""
2=""
[transitions.call0_WHERE.option_nodes]
1="call0_SELECT"
2="call0_GROUP_BY"


[transitions.call0_GROUP_BY]
task="""
"""
[transitions.call0_GROUP_BY.options]
1=""
2=""
[transitions.call0_GROUP_BY.option_nodes]
1="call0_SELECT"
2="call0_HAVING"
