[transitions]


[transitions.call0_FROM]
task="""
Choose whether to include the WHERE clause in the highlighted query.
"""
[transitions.call0_FROM.options]
1="ADD a WHERE clause, allowing for data filtering. Suitable for scenarios requiring specific data subsets before further processing."
2="SKIP this step."
[transitions.call0_FROM.option_nodes]
1="call0_WHERE"
2="WHERE_done"

[transitions.WHERE_done]
task="""
Select whether you would like to make the highlighted query groupped.

You should choose "DO make the query groupped" if you want to use aggregation \
in your current query or you want to add a GROUP BY clause.

Write down the answer to this question: Will the current query need to use an \
aggregate function or a GROUP BY clause to satisfy the task description?
If yes, select "DO make the query groupped".
"""
[transitions.WHERE_done.options]
1="DO make the query groupped."
2="DON'T make the query groupped. You won't be able to use aggregate functions in this query."
[transitions.WHERE_done.option_nodes]
1="call0_GROUP_BY"
2="call0_SELECT"

[transitions.call0_GROUP_BY]
task="""
Select whether you would like to add the HAVING clause.
"""
[transitions.call0_GROUP_BY.options]
1="Add the HAVING clause."
2="OMIT the HAVING clause. You won't be able to add it later."
[transitions.call0_GROUP_BY.option_nodes]
1="call0_HAVING"
2="call0_SELECT"

[call_node_context]

[value_chooser_tasks]
