[transitions]


[transitions.select_datetime_field]
task="""
Select the datetime field.
"""
[transitions.select_datetime_field.options]
1="microseconds"
2="milliseconds"
3="second"
4="minute"
5="hour"
6="day"
7="isodow"
8="week"
9="month"
10="quarter"
11="year"
12="isoyear"
13="decade"
14="century"
15="millennium"
[transitions.select_datetime_field.option_nodes]
1="select_datetime_field_microseconds"
2="select_datetime_field_milliseconds"
3="select_datetime_field_second"
4="select_datetime_field_minute"
5="select_datetime_field_hour"
6="select_datetime_field_day"
7="select_datetime_field_isodow"
8="select_datetime_field_week"
9="select_datetime_field_month"
10="select_datetime_field_quarter"
11="select_datetime_field_year"
12="select_datetime_field_isoyear"
13="select_datetime_field_decade"
14="select_datetime_field_century"
15="select_datetime_field_millennium"


[call_node_context]


[value_chooser_tasks]
