[transitions]


[transitions.timestamp_add_subtract]
task="""
Select the kind of formula you want your timestamp formula to be.
In this list of options, the [date]/[interval] denotes the expression you \
would have to generate next if you select that option. And the option itself \
denotes what will be put in the place of the highlight token.
"""
[transitions.timestamp_add_subtract.options]
1="[date] + [interval]"
2="[date] - [interval]"
[transitions.timestamp_add_subtract.option_nodes]
1="timestamp_add_subtract_plus"
2="timestamp_add_subtract_minus"


[transitions.timestamp_add_subtract_plus]
task="""
Select whether you would like to reverse the order of expressions in the addition operation.
This will not affect the logic of the query, but may be desired for readability purposes.
"""
[transitions.timestamp_add_subtract_plus.options]
1="Do reverse: [interval] + [date]"
2="Don't reverse: [date] + [interval]"
[transitions.timestamp_add_subtract_plus.option_nodes]
1="timestamp_swap_arguments"
2="call94_types"


[call_node_context]
# call94_types=""
# call95_types=""


[value_chooser_tasks]
