[transitions]


[transitions.types]
task="""
Select the SQL data type of the expression that you want \
to generate.

To deduce the correct SQL data type, write down what the expression \
that will replace the highlight token should look like in the end.

After that, answer the question: what is the SQL data type of this expression \
in PostgreSQL?

Finally, select the data type accordingly.

Note that for COUNT you should select bigint.
"""
[transitions.types.options]
1="bigint"
2="integer"
3="numeric"
4="bool"
5="text"
6="date"
7="timestamp"
8="interval"
[transitions.types.option_nodes]
1="types_select_type_bigint"
2="types_select_type_integer"
3="types_select_type_numeric"
4="types_select_type_3vl"
5="types_select_type_text"
6="types_select_type_date"
7="types_select_type_timestamp"
8="types_select_type_interval"


[call_node_context]
# call0_types_value=""


[value_chooser_tasks]
