[transitions]


[transitions.types_type]
task="""
Select the SQL data type of the expressions that you will be generating.

To deduce the correct SQL data type, write down what expressions \
will replace the highlight tokens that are present in the current query and why.
Recall that the highlight tokens should now indicate which fields in the query your \
current decision will affect.

After that, select the biggest type that would fit these expressions.
For example, if you want to generate the "C1 > 3" expression, where C1 \
is of type bigint, and 3 is of type integer, you should select bigint now.
"""
[transitions.types_type.options]
1="bigint"
2="integer"
3="numeric"
4="bool"
5="text"
6="date"
7="timestamp"
8="interval"
[transitions.types_type.option_nodes]
1="types_type_bigint"
2="types_type_integer"
3="types_type_numeric"
4="types_type_3vl"
5="types_type_text"
6="types_type_date"
7="types_type_timestamp"
8="types_type_interval"


[call_node_context]


[value_chooser_tasks]
