[main]
# Running mode. Either "test_ast_to_path", "generate", "train", "syntax_coverage", "semantic_correctness"
mode="semantic_correctness"
# number of queries to generate
num_generate=1000
# count the 2vl-3vl equivalent queries
count_equivalence=true
# measure average query generation time
measure_generation_time=true
# assert parcing the printed AST gives the
# same result (checks validity of AST usage)
assert_parcing_equivalence=true
# (TODO): check the queries run without errors on the schema
assert_runs_on_schema=false
# Pring how many queries were already generated
print_progress=true


[semantic_correctness]
n_tests=10000
schema_path="schema/tpc-h_tables.sql"


[syntax_coverage]
spider_tables_json_path="/Users/mykhailo/Downloads/spider/tables.json"
spider_queries_json_path="/Users/mykhailo/Downloads/spider/train_spider.json"
spider_schemas_folder="/Users/mykhailo/Downloads/spider/schemas/"


[model]
# which model to use. Can be: "subgraph", "full_function_context"
model_name="depthwize_full_function_context"
# whether to use the stacked version of the model
stacked_version=false
# whether to use pretrained model weights
# TODO: apply the same logic as in save_dot_file?
load_weights=true
# where to load the weights from
load_weights_from="weights/depthwize_full_function_context/unstacked/untrained_db_2_performance_graph_100K.mw"
# where to save a dot file with graph representation.
# Type save_dot_file=false to turn off
# save_dot_file="weights_in_dot/subgraph/untrained_db_2_performance_graph_100K.dot"
save_dot_file=false
print_weights_after_training=false


[ast_to_path_testing]
# schema for the testing queries generation
testing_schema="schema/tpc-h_tables.sql"
# number of tests
n_tests=10

[training]
# path to a file with all the training queries separated by ";\n"
# training_db_path="training_dbs/untrained_db.sql"
training_db_path="training_dbs/untrained_db_2_performance_graph_100K.sql"
# schema of the training queries
training_schema="schema/tpc-h_tables.sql"
# where to save model weights to
save_weights_to="weights/fullcontext/unstacked/untrained_db_2_performance_graph_100K.mw"

[query_generator]
# set to false to choose models by maximum probability
use_probabilistic_state_chooser=true
# Whether to use the predictor model for query generation
use_model=false
# print the queries in "generate" mode
print_queries=false
# print the table schema after parcing
print_schema=false
# Path to the file with the database schema
table_schema_path="schema/tpc-h_tables.sql"
# Which substitute model to use as a state selector. Can be: "anticall", "markov".
# Assigns probabilities when the model fails to do so or is absent
substitute_model="anticall"
# aggregate functions settings
aggregate_functions_distribution_map_file="aggregate_functions_distribution_map.json"

[state_generator]
# Path to graph source for a markov chain
graph_file_path="graph.dot"
# graph_file_path="performance_untrained_graph.dot"

[anticall_sub_model]
# anticall dynamic model settings
stir_level=11
p_select_one_smaller=0.0
# stir_level=9
# p_select_one_smaller=0.09818215031911126